# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\stepa\PycharmProjects\CS-cipher\UI\about_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(368, 213)
        self.algoritmButton = QtWidgets.QPushButton(About)
        self.algoritmButton.setGeometry(QtCore.QRect(40, 90, 111, 51))
        self.algoritmButton.setObjectName("algoritmButton")
        self.aboutButton = QtWidgets.QPushButton(About)
        self.aboutButton.setGeometry(QtCore.QRect(200, 90, 111, 51))
        self.aboutButton.setObjectName("aboutButton")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Справка"))
        self.algoritmButton.setText(_translate("About", "Алгоритм"))
        self.aboutButton.setText(_translate("About", "О программе"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    About = QtWidgets.QDialog()
    ui = Ui_About()
    ui.setupUi(About)
    About.show()
    sys.exit(app.exec_())
