# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\stepa\PycharmProjects\CS-cipher\UI\file_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from CSCipher import CSCipher


class Ui_FileDialog(object):
    outputFile: str or None
    inputFile: str or None
    keyFile: str or None

    def __init__(self):
        self.outputFile = None
        self.inputFile = None
        self.keyFile = None

    def setupUi(self, FileDialog):
        FileDialog.setObjectName("FileDialog")
        FileDialog.resize(369, 180)
        self.inputFileButton = QtWidgets.QPushButton(FileDialog)
        self.inputFileButton.setGeometry(QtCore.QRect(20, 30, 75, 51))
        self.inputFileButton.setObjectName("inputFileButton")
        self.outputFileButton = QtWidgets.QPushButton(FileDialog)
        self.outputFileButton.setGeometry(QtCore.QRect(240, 30, 75, 51))
        self.outputFileButton.setObjectName("outputFileButton")
        self.keyFileButton = QtWidgets.QPushButton(FileDialog)
        self.keyFileButton.setGeometry(QtCore.QRect(130, 30, 75, 51))
        self.keyFileButton.setObjectName("keyFileButton")
        self.startButton = QtWidgets.QPushButton(FileDialog)
        self.startButton.setGeometry(QtCore.QRect(130, 140, 75, 23))
        self.startButton.setObjectName("startButton")
        self.generateBox = QtWidgets.QCheckBox(FileDialog)
        self.generateBox.setEnabled(False)
        self.generateBox.setGeometry(QtCore.QRect(230, 110, 131, 31))
        self.generateBox.setObjectName("generateBox")
        self.encryptBox = QtWidgets.QCheckBox(FileDialog)
        self.encryptBox.setGeometry(QtCore.QRect(230, 90, 101, 17))
        self.encryptBox.setObjectName("encryptBox")

        self.retranslateUi(FileDialog)
        QtCore.QMetaObject.connectSlotsByName(FileDialog)

    def retranslateUi(self, FileDialog):
        _translate = QtCore.QCoreApplication.translate
        FileDialog.setWindowTitle(_translate("FileDialog", "Файл"))
        self.inputFileButton.setText(_translate("FileDialog", "Выберите\nвходной\nфайл"))
        self.outputFileButton.setText(_translate("FileDialog", "Выберите\nвыходной\nфайл"))
        self.keyFileButton.setText(_translate("FileDialog", "Выберите\nфайл с\nключем"))
        self.startButton.setText(_translate("FileDialog", "Начать"))
        self.generateBox.setText(_translate("FileDialog", "Сгенерировать ключ"))
        self.encryptBox.setText(_translate("FileDialog", "Зашифровать"))
        self.encryptBox.stateChanged.connect(self.onCheckedGenerate)
        self.inputFileButton.clicked.connect(self.onInputClick)
        self.keyFileButton.clicked.connect(self.onKeyClick)
        self.outputFileButton.clicked.connect(self.onOutputClick)
        self.startButton.clicked.connect(self.onStartClick)

    def onInputClick(self):
        self.inputFile = QtWidgets.QFileDialog.getOpenFileName(filter='*.txt')[0]

    def onKeyClick(self):
        self.keyFile = QtWidgets.QFileDialog.getOpenFileName(filter='*.txt')[0]

    def onOutputClick(self):
        self.outputFile = QtWidgets.QFileDialog.getOpenFileName(filter='*.txt')[0]

    def onStartClick(self):
        encrypt = self.encryptBox.isChecked()
        if self.outputFile is None:
            self.outputFile = 'output.txt'
        cs = CSCipher(self.inputFile, self.keyFile, self.outputFile,not encrypt)
        cs.start()
        QMessageBox.about(FileDialog, "", "Готово")
        self.outputFile = None
        self.keyFile = None
        self.inputFile = None

    def onCheckedGenerate(self):
        if self.encryptBox.isChecked():
            self.generateBox.setEnabled(True)
        else:
            self.generateBox.setChecked(False)
            self.generateBox.setEnabled(False)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    FileDialog = QtWidgets.QDialog()
    ui = Ui_FileDialog()
    ui.setupUi(FileDialog)
    FileDialog.show()
    sys.exit(app.exec_())
